CREATE TABLE task_generation_job (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL,
    orchard_id BIGINT NOT NULL,
    task_date DATE NOT NULL,
    focus VARCHAR(500),
    save_as_draft BOOLEAN NOT NULL,
    requested_by BIGINT NOT NULL,
    status VARCHAR(16) NOT NULL,
    weather_summary VARCHAR(1000),
    phenology VARCHAR(32),
    citations_json TEXT,
    error_message VARCHAR(1000),
    started_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_task_generation_batch UNIQUE (batch_id),
    CONSTRAINT uk_task_generation_orchard_date UNIQUE (orchard_id, task_date),
    CONSTRAINT ck_task_generation_status CHECK (status IN ('PROCESSING', 'COMPLETED', 'FAILED')),
    CONSTRAINT fk_task_generation_orchard FOREIGN KEY (orchard_id) REFERENCES orchard(id),
    CONSTRAINT fk_task_generation_requester FOREIGN KEY (requested_by) REFERENCES app_user(id)
);

CREATE INDEX idx_task_generation_status ON task_generation_job (status, created_at);
