CREATE TABLE account_recovery_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_type VARCHAR(16) NOT NULL,
    requested_username VARCHAR(64),
    display_name VARCHAR(64) NOT NULL,
    contact VARCHAR(128) NOT NULL,
    note VARCHAR(500),
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    handled_by BIGINT,
    handled_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_account_recovery_type CHECK (request_type IN ('ACCOUNT', 'PASSWORD')),
    CONSTRAINT ck_account_recovery_status CHECK (status IN ('PENDING', 'COMPLETED', 'REJECTED')),
    CONSTRAINT fk_account_recovery_handler FOREIGN KEY (handled_by) REFERENCES app_user(id)
);

CREATE INDEX idx_account_recovery_status_created
    ON account_recovery_request (status, created_at);
