CREATE TABLE IF NOT EXISTS sys_operation_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_name VARCHAR(64) NOT NULL,
    operation_name VARCHAR(128) NOT NULL,
    operator_name VARCHAR(64),
    request_id VARCHAR(64),
    success BOOLEAN NOT NULL DEFAULT TRUE,
    detail VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_operation_log_created_at ON sys_operation_log (created_at);
CREATE INDEX IF NOT EXISTS idx_operation_log_module ON sys_operation_log (module_name);

