-- 果园表
CREATE TABLE orchard (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    area_mu DECIMAL(10, 2) NOT NULL,
    tree_count INT NOT NULL,
    tree_age_years INT,
    variety VARCHAR(64),
    planting_mode VARCHAR(64),
    irrigation_mode VARCHAR(64),
    planting_date DATE,
    province VARCHAR(64),
    city VARCHAR(64),
    district VARCHAR(64),
    longitude DOUBLE PRECISION,
    latitude DOUBLE PRECISION,
    manager_name VARCHAR(64),
    status VARCHAR(16) NOT NULL DEFAULT 'ENABLED',
    current_phenology VARCHAR(32) NOT NULL DEFAULT 'FRUIT_EXPANSION',
    phenology_effective_date DATE,
    remark VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- 物候期记录表
CREATE TABLE phenology_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orchard_id BIGINT NOT NULL,
    phenology VARCHAR(32) NOT NULL,
    effective_date DATE NOT NULL,
    remark VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_phenology_orchard FOREIGN KEY (orchard_id) REFERENCES orchard(id)
);

CREATE INDEX idx_phenology_orchard ON phenology_record (orchard_id);

-- 实训记录表
CREATE TABLE training_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    orchard_id BIGINT NOT NULL,
    task_id BIGINT,
    record_date DATE NOT NULL,
    inspected_tree_count INT,
    abnormal_tree_count INT,
    image_url VARCHAR(512),
    phenomenon VARCHAR(1000),
    measure VARCHAR(1000),
    result VARCHAR(1000),
    comment VARCHAR(1000),
    score INT,
    review_status VARCHAR(32) DEFAULT 'PENDING',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_training_orchard ON training_record (orchard_id);
CREATE INDEX idx_training_student ON training_record (student_id);
CREATE INDEX idx_training_date ON training_record (record_date);

-- 文件记录表
CREATE TABLE file_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_name VARCHAR(255) NOT NULL,
    stored_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(64) NOT NULL,
    file_size BIGINT NOT NULL,
    storage_path VARCHAR(500) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    uploader_id BIGINT NOT NULL DEFAULT 0
);