CREATE TABLE model_call_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider VARCHAR(16) NOT NULL,
    model_name VARCHAR(128) NOT NULL,
    operation_type VARCHAR(16) NOT NULL,
    success BOOLEAN NOT NULL,
    duration_ms BIGINT NOT NULL,
    input_tokens INT,
    output_tokens INT,
    total_tokens INT,
    error_summary VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_model_call_log_created_at ON model_call_log (created_at);
CREATE INDEX idx_model_call_log_operation ON model_call_log (operation_type);
