CREATE TABLE tool_call_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT,
    tool_name VARCHAR(64) NOT NULL,
    input_summary VARCHAR(1000),
    output_summary VARCHAR(1000),
    status VARCHAR(16) NOT NULL,
    duration_ms BIGINT NOT NULL,
    error_summary VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_tool_call_log_session ON tool_call_log (session_id);
CREATE INDEX idx_tool_call_log_created_at ON tool_call_log (created_at);
