CREATE TABLE chat_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    orchard_id BIGINT NOT NULL,
    title VARCHAR(100) NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_chat_session_user FOREIGN KEY (user_id) REFERENCES app_user(id),
    CONSTRAINT fk_chat_session_orchard FOREIGN KEY (orchard_id) REFERENCES orchard(id)
);

CREATE INDEX idx_chat_session_user ON chat_session (user_id, deleted);
CREATE INDEX idx_chat_session_orchard ON chat_session (orchard_id);

CREATE TABLE chat_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    role VARCHAR(16) NOT NULL,
    content TEXT NOT NULL,
    status VARCHAR(16) NOT NULL,
    model VARCHAR(128),
    duration_ms BIGINT,
    finish_reason VARCHAR(32),
    error_summary VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_chat_message_session FOREIGN KEY (session_id) REFERENCES chat_session(id)
);

CREATE INDEX idx_chat_message_session ON chat_message (session_id, created_at);

ALTER TABLE tool_call_log
    ADD CONSTRAINT fk_tool_call_session FOREIGN KEY (session_id) REFERENCES chat_session(id);
