CREATE TABLE knowledge_document (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    source_organization VARCHAR(200) NOT NULL,
    publish_date DATE,
    region VARCHAR(100),
    phenology VARCHAR(32),
    document_type VARCHAR(64) NOT NULL,
    original_name VARCHAR(255) NOT NULL,
    file_type VARCHAR(16) NOT NULL,
    storage_path VARCHAR(500) NOT NULL,
    status VARCHAR(16) NOT NULL,
    chunk_count INT NOT NULL DEFAULT 0,
    failure_reason VARCHAR(1000),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_knowledge_document_status ON knowledge_document (status, deleted);

CREATE TABLE knowledge_chunk (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    chunk_index INT NOT NULL,
    content TEXT NOT NULL,
    page_number INT,
    region VARCHAR(100),
    phenology VARCHAR(32),
    document_type VARCHAR(64),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_knowledge_chunk_document FOREIGN KEY (document_id) REFERENCES knowledge_document(id),
    CONSTRAINT uk_knowledge_chunk_index UNIQUE (document_id, chunk_index)
);

CREATE INDEX idx_knowledge_chunk_document ON knowledge_chunk (document_id);
CREATE INDEX idx_knowledge_chunk_metadata ON knowledge_chunk (phenology, region, document_type);
