CREATE TABLE farming_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL,
    orchard_id BIGINT NOT NULL,
    task_date DATE NOT NULL,
    type VARCHAR(64) NOT NULL,
    title VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    priority VARCHAR(16) NOT NULL,
    suggested_time VARCHAR(100),
    status VARCHAR(16) NOT NULL,
    basis TEXT,
    safety_notice VARCHAR(1000),
    status_remark VARCHAR(500),
    assignee_id BIGINT,
    generated_by BIGINT NOT NULL,
    citations_json TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_farming_task_orchard FOREIGN KEY (orchard_id) REFERENCES orchard(id),
    CONSTRAINT fk_farming_task_generator FOREIGN KEY (generated_by) REFERENCES app_user(id),
    CONSTRAINT fk_farming_task_assignee FOREIGN KEY (assignee_id) REFERENCES app_user(id)
);

CREATE INDEX idx_farming_task_filters ON farming_task (orchard_id, task_date, status);
CREATE INDEX idx_farming_task_batch ON farming_task (batch_id);

ALTER TABLE training_record
    ADD CONSTRAINT fk_training_record_task FOREIGN KEY (task_id) REFERENCES farming_task(id);
