<script setup lang="ts">
import { reactive,ref } from 'vue'
import api,{unwrap} from '@/api'
import { Operation } from '@element-plus/icons-vue'
const active=ref('irrigation'),loading=ref(false),result=ref<any>(null)
const forms=reactive({irrigation:{treeCount:300,litersPerTree:20},fertilizer:{treeCount:300,amountPerTree:12,unit:'KG'},dilution:{solutionLiters:200,dilutionRatio:1000},yield:{sampleTrees:30,averageKgPerTree:45,totalTrees:300}})
const configs:any={irrigation:{title:'灌溉量',endpoint:'/calculators/irrigation'},fertilizer:{title:'肥料总量',endpoint:'/calculators/fertilizer'},dilution:{title:'药剂稀释',endpoint:'/calculators/dilution'},yield:{title:'产量估算',endpoint:'/calculators/yield-estimate'}}
async function calculate(){loading.value=true;try{result.value=unwrap<any>(await api.post(configs[active.value].endpoint,(forms as any)[active.value]))}finally{loading.value=false}}
</script>
<template><div><div class="page-title-row"><div><h2>农业用量计算</h2><p>统一使用后端 BigDecimal 计算服务</p></div></div><div class="calculator-layout"><aside class="calc-tabs"><button v-for="(c,key) in configs" :key="key" :class="{active:String(key)===active}" @click="active=String(key);result=null">{{c.title}}</button></aside><section class="panel calc-panel"><header class="panel-header"><h3>{{configs[active].title}}</h3><span class="status-pill">精确计算</span></header><div class="calc-form">
  <el-form v-if="active==='irrigation'" label-position="top"><el-form-item label="果园株数"><el-input-number v-model="forms.irrigation.treeCount" :min="1"/></el-form-item><el-form-item label="单株用水量（升）"><el-input-number v-model="forms.irrigation.litersPerTree" :min="0.01" :step="1"/></el-form-item></el-form>
  <el-form v-if="active==='fertilizer'" label-position="top"><el-form-item label="果园株数"><el-input-number v-model="forms.fertilizer.treeCount" :min="1"/></el-form-item><el-form-item label="单株用量"><el-input-number v-model="forms.fertilizer.amountPerTree" :min="0.01"/></el-form-item><el-form-item label="单位"><el-segmented v-model="forms.fertilizer.unit" :options="[{label:'克',value:'G'},{label:'千克',value:'KG'}]"/></el-form-item></el-form>
  <el-form v-if="active==='dilution'" label-position="top"><el-form-item label="目标药液体积（升）"><el-input-number v-model="forms.dilution.solutionLiters" :min="0.01"/></el-form-item><el-form-item label="稀释倍数"><el-input-number v-model="forms.dilution.dilutionRatio" :min="2" :step="100"/></el-form-item></el-form>
  <el-form v-if="active==='yield'" label-position="top"><el-form-item label="抽样株数"><el-input-number v-model="forms.yield.sampleTrees" :min="1"/></el-form-item><el-form-item label="平均单株产量（千克）"><el-input-number v-model="forms.yield.averageKgPerTree" :min="0.01"/></el-form-item><el-form-item label="果园总株数"><el-input-number v-model="forms.yield.totalTrees" :min="1"/></el-form-item></el-form>
  <el-button type="primary" :icon="Operation" :loading="loading" @click="calculate">计算</el-button>
</div></section><section class="result-area"><div v-if="!result" class="result-empty"><el-icon><Operation/></el-icon><span>等待计算</span></div><template v-else><p class="eyebrow">计算结果</p><h3>{{result.formula}}</h3><div class="result-grid"><div v-for="(value,key) in result.result" :key="key"><span>{{key}}</span><strong>{{value}}</strong></div></div><el-alert :title="result.safetyNotice" type="warning" :closable="false" show-icon/></template></section></div></div></template>
<style scoped>.calculator-layout{display:grid;grid-template-columns:150px minmax(320px,.75fr) minmax(360px,1fr);gap:16px;align-items:stretch}.calc-tabs{display:flex;flex-direction:column;gap:5px}.calc-tabs button{border:1px solid var(--line);background:#fff;border-radius:5px;text-align:left;padding:14px;color:var(--muted)}.calc-tabs button.active{color:var(--green);border-color:var(--green);font-weight:700;box-shadow:inset 3px 0 var(--green)}.calc-form{padding:20px}.calc-form .el-input-number{width:100%}.result-area{background:#26342e;color:white;border-radius:6px;padding:26px;min-height:380px}.result-area .eyebrow{color:#b6cf82}.result-area h3{font-size:15px;font-weight:500;color:#dfe8e2;margin:10px 0 26px}.result-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-bottom:22px}.result-grid>div{background:#31443b;border:1px solid #42584e;border-radius:5px;padding:14px;display:flex;flex-direction:column;gap:7px}.result-grid span{font-size:10px;color:#a9b9b0}.result-grid strong{font-size:19px}.result-empty{height:100%;display:grid;place-content:center;justify-items:center;gap:10px;color:#8fa097}.result-empty .el-icon{font-size:36px}@media(max-width:1000px){.calculator-layout{grid-template-columns:130px 1fr}.result-area{grid-column:1/-1;min-height:260px}}@media(max-width:600px){.calculator-layout{grid-template-columns:1fr}.calc-tabs{display:grid;grid-template-columns:1fr 1fr}.result-area{grid-column:auto}.result-grid{grid-template-columns:1fr}}</style>
